# Generated by Django 5.2.4 on 2025-07-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('full_name', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='comment_images/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
